CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"
OPTION_TOKEN_INDEX = -500
QUESTION_TOKEN_INDEX = -600
CONTEXT_TOKEN_INDEX = -700
OPTION_AND_QUESTION_TOKEN_INDEX = -800

CONTEXT_AND_QUESTION_AND_OPTION_TOKEN_INDEX = -900



